name: docs CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-module-docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build V
        run: git clone https://github.com/vlang/v ../v && cd ../v && make
      - name: Craft documentation
        run: ../v/v doc -m -f html . && mv _docs/.html _docs/index.html
      - name: Fix search
        run: sed -i 's/\.html//g' _docs/search_index.js
      - name: Fix title
        run: sed -i 's/ | vdoc/vom | vdoc/' _docs/index.html
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.9
        with:
          branch: docs
          folder: _docs


